[package]
name = "rv32i"
version = "0.1.0"
authors = ["Tock Project Developers <tock-dev@googlegroups.com>"]
edition = "2018"

[dependencies]
kernel = { path = "../../kernel" }
tock_rt0 = { path = "../../libraries/tock-rt0" }
riscvregs = { git = "https://github.com/DieracDelta/riscvregs.git", rev = "2c35ea8" }
