[package]
name = "hifive1"
version = "0.1.0"
authors = ["Tock Project Developers <tock-dev@googlegroups.com>"]
build = "build.rs"
edition = "2018"

[target.riscv32ima-unknown-none-elf]
linker = "rust-lld"

[profile.dev]
panic = "abort"
lto = false
opt-level = "z"
debug = true

[profile.release]
panic = "abort"
lto = true
opt-level = "z"
debug = true

[dependencies]
rv32i = { path = "../../arch/rv32i" }
capsules = { path = "../../capsules" }
kernel = { path = "../../kernel" }
e310x = { path = "../../chips/e310x" }
sifive = { path = "../../chips/sifive" }
riscvregs = { git = "https://github.com/DieracDelta/riscvregs.git", rev = "c03eb6c"}
